runtime: python
env: flex
# the PROJECT-DIRECTORY is the one with settings.py and wsgi.py
entrypoint: gunicorn -b :$PORT landingsite.wsgi # specific to a GUnicorn HTTP server deployment

# any environment variables you want to pass to your application.
# accessible through os.environ['VARIABLE_NAME']
env_variables:
  ENGINE_DJANGO: 'django.db.backends.mysql'
  SECRET_KEY: ''
  BUCKET_NAME: ''
# everything after /cloudsql/ can be found by entering >> gcloud sql instances describe DATABASE-NAME << in your Terminal
# the DATABASE-NAME is the name you gave your project's PostgreSQL database
# the second line from the describe output called connectionName can be copied and pasted after /cloudsql/
  DB_HOST: '/cloudsql/tevdevelops:europe-west2:tevinstance'
  DB_PORT: '3306' # '3306' MYSQL port - '5432'  PostgreSQL port
  DB_NAME: 'Developers'
  DB_USER: '' # either 'postgres' (default) or one you created on the PostgreSQL instance page
  DB_PASSWORD: ''
  
  STATIC_URL: 'https://storage.googleapis.com/tevstudio-static/static/' # this is the url that you sync static files to

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
  - url: /static
    static_dir: static

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.

  - url: /.*
    script: auto


beta_settings:
# from command >> gcloud sql instances describe tevinstance <<

  cloud_sql_instances: tevdevelops:europe-west2:tevinstance

#  cloud_sql_instances: <INSTANCE_CONNECTION_NAME>=tcp:<TCP_PORT> provides a local tcp port (127.0.0.1:<TCP_PORT>)

runtime_config:
  python_version: 3
